export const colors = {
  primary: '#ad1830',
  primaryDark: '#8f1024',
  primarySoft: '#c43a50',
  primaryTint: '#f7dce2',
  danger: '#d12a36',
  warning: '#f59e0b',
  success: '#19a66a',
  info: '#3b6fc4',
  white: '#ffffff',
  darkText: '#141821',
  mutedText: '#606875',
  lightBackground: '#f5f6f8',
  darkBackground: '#0f1217',
  lightCard: '#ffffff',
  darkCard: '#181c22',
  lightBorder: '#e1e5ea',
  darkBorder: '#2b313b',
  sidebarLight: '#ad1830',
  sidebarLightDeep: '#8f1024',
  sidebarDark: '#17131a',
  sidebarDarkPanel: '#261923',
  sidebarDarkBorder: '#4b2634',
  tabLight: '#fff4f6',
  tabDark: '#171d25',
};

export const theme = {
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    pill: 999,
  },
  spacing: {
    xs: 6,
    sm: 10,
    md: 16,
    lg: 22,
    xl: 28,
  },
  shadow: {
    light: {
      shadowColor: '#111827',
      shadowOpacity: 0.08,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 7 },
      elevation: 3,
    },
    dark: {
      shadowColor: '#000000',
      shadowOpacity: 0.24,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 7 },
      elevation: 2,
    },
  },
};

export const getThemeColors = (isDarkMode, overrides = {}) => ({
  background: isDarkMode ? colors.darkBackground : colors.lightBackground,
  text: isDarkMode ? '#f8fafc' : colors.darkText,
  title: isDarkMode ? colors.white : colors.primaryDark,
  card: isDarkMode ? colors.darkCard : colors.lightCard,
  cardAlt: isDarkMode ? '#202630' : '#f9fafb',
  subText: isDarkMode ? '#aeb7c5' : colors.mutedText,
  border: isDarkMode ? colors.darkBorder : colors.lightBorder,
  divider: isDarkMode ? '#262c35' : '#e6e8ed',
  tabContainer: isDarkMode ? colors.tabDark : colors.tabLight,
  activeTab: colors.primary,
  sidebar: isDarkMode ? colors.sidebarDark : colors.sidebarLight,
  sidebarPanel: isDarkMode ? colors.sidebarDarkPanel : 'rgba(255, 255, 255, 0.14)',
  sidebarText: colors.white,
  sidebarMuted: isDarkMode ? '#c0b5bd' : '#ffd9df',
  sidebarBorder: isDarkMode ? colors.sidebarDarkBorder : 'rgba(255, 255, 255, 0.25)',
  chip: isDarkMode ? '#2a2f37' : '#2f2f32',
  chipText: colors.white,
  input: isDarkMode ? '#111720' : colors.white,
  progressTrack: isDarkMode ? '#2b313a' : '#e1e3e7',
  shadow: isDarkMode ? theme.shadow.dark : theme.shadow.light,
  ...overrides,
});

export const animation = {
  duration: 400,
};

export const sharedStyles = {
  container: { flex: 1 },
  content: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 18,
  },
  contentContainer: { paddingBottom: 28 },
  centerContent: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  statusContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    padding: 24,
  },
  statusTitle: {
    fontSize: 18,
    fontWeight: '800',
    textAlign: 'center',
  },
  statusText: {
    color: colors.mutedText,
    fontSize: 14,
    textAlign: 'center',
  },

  pageHeader: {
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 16,
    borderBottomWidth: 1,
  },
  mobileHeader: {
    borderBottomWidth: 1,
  },
  mobileTopBar: {
    minHeight: 62,
    paddingHorizontal: 16,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  mobileHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  mobileIconButton: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mobilePageTitle: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 11,
  },
  mobileTitle: { fontSize: 20, fontWeight: '900', letterSpacing: 0 },
  mobileSubtitle: { fontSize: 12, marginTop: 2 },
  pageHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 14,
  },
  pageHeaderText: {
    flex: 1,
    minWidth: 0,
  },
  eyebrow: {
    color: colors.primarySoft,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0,
    textTransform: 'uppercase',
    marginBottom: 3,
  },
  title: { fontSize: 24, fontWeight: '900', letterSpacing: 0 },
  subtitle: { fontSize: 13, marginTop: 4, marginBottom: 0 },
  headerActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    gap: 8,
    maxWidth: 420,
  },
  chip: {
    minHeight: 38,
    borderRadius: theme.radius.pill,
    paddingHorizontal: 14,
    paddingVertical: 9,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  chipText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: '800',
  },
  themeToggle: {
    minHeight: 38,
    borderRadius: theme.radius.md,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderWidth: 1,
  },
  themeToggleText: { fontSize: 12, fontWeight: '800' },
  mobileIdentity: {
    borderRadius: theme.radius.lg,
    padding: 14,
    marginBottom: 14,
    borderWidth: 1,
  },
  mobileBrandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  brandBlock: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    minWidth: 0,
  },
  logoMark: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  logoMarkText: { color: colors.white, fontSize: 16, fontWeight: '900' },
  brandName: { color: colors.white, fontSize: 20, fontWeight: '900' },
  brandSub: { color: '#ffdce1', fontSize: 12, fontWeight: '700' },
  userMini: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
    padding: 12,
    borderRadius: theme.radius.md,
    borderWidth: 1,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  avatarText: { color: colors.white, fontWeight: '900', fontSize: 14 },
  userName: { color: colors.white, fontSize: 15, fontWeight: '900' },
  userRa: { color: '#ffdce1', fontSize: 12, fontWeight: '700', marginTop: 2 },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },

  sectionTitle: { fontSize: 18, fontWeight: '900', letterSpacing: 0 },
  sectionEyebrow: {
    color: colors.primarySoft,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },

  rowCenter: { flexDirection: 'row', alignItems: 'center' },
  cardHeaderBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 10,
    gap: 12,
  },
  surfaceCard: {
    borderWidth: 1,
    borderRadius: theme.radius.md,
    padding: 16,
  },

  tabContainer: {
    flexDirection: 'row',
    alignSelf: 'flex-start',
    borderRadius: theme.radius.md,
    padding: 4,
    marginBottom: 18,
    borderWidth: 1,
  },
  tab: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9,
    minHeight: 40,
  },
  tabText: { color: colors.mutedText, fontWeight: '800', fontSize: 13 },
  activeTabText: { color: colors.white, fontWeight: '900' },

  badge: {
    backgroundColor: colors.primary,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: theme.radius.pill,
    alignSelf: 'flex-start',
  },
  badgeText: { color: colors.white, fontSize: 11, fontWeight: '900' },

  primaryButton: {
    backgroundColor: colors.primary,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: theme.radius.sm,
    minHeight: 44,
  },
  primaryButtonText: { color: colors.white, fontWeight: '900', fontSize: 14 },
};
